### ISSUE TITLE
Создавать папки отдельно и давать выбирать их при создании группы

### ISSUE THREAD

**Issue by ivanmem** [ivanmem/communitykeeper-vue#2]
```
1) Создать блок с добавлением папок.
2) В блоке добавления группы заменить текстовый выбор папки на select. Пока компонента выбора нет - используем html <select>. Добавить такую же кнопку "Добавить", но для добавления папки. 
3) Перенести кнопку Сохранить изменения вниз.
```

**Comment by xeleoss** [comment]
1) Создать блок с добавлением папок.
2) В блоке добавления группы заменить текстовый выбор папки на select. Пока компонента выбора нет - используем html <select>. Добавить такую же кнопку "Добавить", но для добавления папки. 
3) Перенести кнопку Сохранить изменения вниз

**Comment by ivanmem** [comment]
Всё решилось проще, там теперь подсказки. Осталось исправить их отображение. Они налезают на сам инпут почему-то.
